### ISSUE TITLE
Missing word between segments

### ISSUE THREAD

**Issue by lociii** [Harras3/unhallucinated-faster-whisper#1]
Hey there,

First, thanks for your work on the library. \
When trying it out, I had issues with missing words between segments.

I was running in a docker container
```Dockerfile
FROM nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04

RUN apt -y update && \
    apt -y --no-install-recommends install build-essential python3-pip && \
    apt clean && \
    find /usr/share/man /usr/share/locale /usr/share/doc -type f -delete && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN groupadd -f app && \
    useradd -m -g app app && \
    chown app:app /app

USER app

COPY --chown=app requirements* /app/

RUN pip install --no-cache-dir --no-compile --upgrade unhallucinated-faster-whisper
```

```yaml
services:
  app:
    build:
      context: .
    # user: app
    entrypoint: ""
    command: sleep infinity
    volumes:
      - .:/app:cached
    networks:
      - whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  whisper:
```

Using the following Python code

```python
from faster_whisper import WhisperModel

model = WhisperModel("large", device="cuda")
segments, info = model.transcribe("audio.mp3", unhallucinated=True)

for segment in segments:
    print(segment.text)
```

Example file taken from https://listenaminute.com/b/banks.html \
Line breaks where segments break.

```
want a loan the bank i banked
 mistakes with my account
```

should be

```
want a loan the bank i bank
with make dozens of mistakes with my account
```
